Nombre = input ("Ingrese su Nombre ")
Apellido = input ("Ingrese su Apellido " )
Carrera = input ("Ingrese Carrera que cursa actual ")
Asignatura = input ("Ingrese su Asignatura ")
Sede = input ("Ingrese su Sede de Inacap ")
Semestre = input ("Ingrese Semestre cursado actual ")
Año = input ("Ingrese año actual ")
Ciudad =input ("Ingrese su Ciudad ")
Edad = input ("Ingrese su Edad ")
print ("Hola " + Nombre, Apellido + " De La Carrera "+ Carrera+ " Cursando " + Asignatura + " En la Sede " +Sede + " Del Semestre "+Semestre+" En el año "+Año+ " Ubicado en la cuidad " +Ciudad+ " y Tienes "+Edad+" años " )
